"""add tracker device management

Revision ID: a1735574f91f
Revises: 8f0a93cdfbc0
Create Date: 2026-08-16 11:21:28.426489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1735574f91f'
down_revision: Union[str, Sequence[str], None] = '8f0a93cdfbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sa.String(length=150), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_device_id', sa.String(length=150), nullable=True),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('sim_iccid', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_communication_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'serial_number', name='uq_tracker_devices_organization_serial'),
    sa.UniqueConstraint('provider', 'provider_device_id', name='uq_tracker_devices_provider_device_id')
    )
    op.create_index(op.f('ix_tracker_devices_asset_id'), 'tracker_devices', ['asset_id'], unique=True)
    op.create_index(op.f('ix_tracker_devices_imei'), 'tracker_devices', ['imei'], unique=True)
    op.create_index(op.f('ix_tracker_devices_last_communication_at'), 'tracker_devices', ['last_communication_at'], unique=False)
    op.create_index(op.f('ix_tracker_devices_organization_id'), 'tracker_devices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tracker_devices_sim_iccid'), 'tracker_devices', ['sim_iccid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_devices_sim_iccid'), table_name='tracker_devices')
    op.drop_index(op.f('ix_tracker_devices_organization_id'), table_name='tracker_devices')
    op.drop_index(op.f('ix_tracker_devices_last_communication_at'), table_name='tracker_devices')
    op.drop_index(op.f('ix_tracker_devices_imei'), table_name='tracker_devices')
    op.drop_index(op.f('ix_tracker_devices_asset_id'), table_name='tracker_devices')
    op.drop_table('tracker_devices')
    # ### end Alembic commands ###
